### ISSUE TITLE
Dark Theme does not apply correctly!

### ISSUE THREAD

**Issue by aimproxy** [aggalex/Contacts#14]
If you enable the Dark Theme we does not apply correctly, and if you could add a ModeSwitch Button will be great to change the theme!

**Comment by ryonakano** [comment]
![Screenshot from 2019-07-22 00-05-26](https://user-images.githubusercontent.com/26003928/61592947-6ed09e80-ac14-11e9-97a6-234b9ce0508f.png)

**Comment by aggalex** [comment]
I don't think a contacts app needs a dark theme necessarily because it's not an app that specializes in media or if required to be open long hours. I have however fixed the import/export box. But I don't think such a switch would be suitable for this app. I'll make the app dark theme friendly only to make sure things won't look out of place when elementary officially adds a global dark theme preference, or for the people who use elementary tweaks.
